name: ipympl-dev
channels:
    - conda-forge
dependencies:
    - pip
    - yarn
    - jupyter-packaging
    - jupyterlab=3
    - ipywidgets>=7.6
    - pillow
    - numpy
    - matplotlib
    - flake8
    - pytest
    - nbval
    - pre-commit
    - pip:
        - build
        - myst-nb
        - Sphinx >= 1.5
        - sphinx-copybutton
        - sphinx-panels
        - sphinx-thebe
        - sphinx-togglebutton
        - sphinx-book-theme
        - sphinx-autobuild
